import type { Metadata } from 'next';
import './globals.css';
import { geistMono, geistSans, neueMachina } from '@/lib/fonts';
import { cn } from '@/lib/utils';
import Footer from '@/components/global/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={cn('antialiased font-sans', geistSans.variable, geistMono.variable, neueMachina.variable)}>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
